<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Introduction</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>

<!-- MathJax scripts -->
<script type="text/javascript" src="https://cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML">
</script>


<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{2. medExtractR Vignette for tapering extension of medExtractR function}
%\VignetteEncoding{UTF-8}
-->

<h2>Introduction</h2>

<p>The <code>medExtractR</code> package uses a natural language processing (NLP) system called <em>medExtractR</em>.\(^{1}\) This system is a medication extraction system that uses regular expressions and rule-based approaches to identify key dosing information including drug name, strength, dose amount, frequency or intake time, dose change, and last dose time. In this vignette, we introduce the <code>medExtractR_tapering</code> function, an extension on the basic <code>medExtractR</code> function. The goal of this function is to extract more information for drugs following a tapering schedule. Some drugs (e.g., steroids, antidepressants) require weaning schedules to be gradually stopped in order to avoid adverse side effects or withdrawal symptoms. Tapering schedules are much more complex and require more entities in order to build longitudinal dose data. </p>

<!-- Post-processing features exist in the `EHR`$^{2}$ R package which convert the `medExtractR_tapering` output into longitudinal dose diaries, making it usable for PK/PD analyses.  -->

<h2>Tapering extension to <code>medExtractR</code></h2>

<p>Similar to <code>medExtractR</code>&#39;s <code>extract_entities</code> subfunction, the tapering extension has its own corresponding subfunction called <code>extract_entities_tapering</code>. In addition to the entities identified by the basic <code>medExtractR</code>  function, the tapering extension can also identify: dispense amount (entity name in output: &ldquo;DispenseAmt&rdquo;); number of refills (&ldquo;Refill&rdquo;); keywords indicating a particular dose schedule pattern, such as &ldquo;taper&rdquo;, &ldquo;wean&rdquo;, &ldquo;dose pack&rdquo;, or &ldquo;discontinue&rdquo; (&ldquo;DoseSchedule&rdquo;); keywords indicating whether a dose is past, current, or future (&ldquo;TimeKeyword&rdquo;); words or symbols linking consecutive doses in a tapering schedule (&ldquo;Transition&rdquo;); and prepositions adjacent to other entities (&ldquo;Preposition&rdquo;), used in some contexts to preserve or infer meaning. </p>

<pre><code class="r">library(medExtractR)

# prednisone tapering note file name
pred_fn &lt;- c(
  system.file(&quot;examples&quot;, &quot;predpid1_2013-04-27_note1_1.txt&quot;, package = &quot;medExtractR&quot;),
  system.file(&quot;examples&quot;, &quot;predpid2_2015-12-11_note1_1.txt&quot;, package = &quot;medExtractR&quot;),
  system.file(&quot;examples&quot;, &quot;predpid3_2017-01-01_note1_1.txt&quot;, package = &quot;medExtractR&quot;)
)

# execute medExtractR_tapering
pred_mxr &lt;- do.call(rbind, lapply(pred_fn, function(filename){
  pred_note &lt;- paste(scan(filename, &#39;&#39;, sep = &#39;\n&#39;, quiet = TRUE), collapse = &#39;\n&#39;)
  fn &lt;- sub(&quot;.+/&quot;, &quot;&quot;, filename)
  cbind(&quot;filename&quot; = fn,
        medExtractR_tapering(note = pred_note,
                             drug_names = c(&quot;prednisone&quot;, &quot;pred&quot;),
                             unit = &quot;mg&quot;))
}))
</code></pre>

<p>This extended function was created to handle three common patterns of dosing found in notes for patients being treated with medications that commonly use a tapering schedule to gradually decrease the patient&#39;s dose. The drug prednisone is an example of one such medication, and de-identified notes for patients being treated with prednisone were used during <code>medExtractR_tapering</code> development (described in a later section). We call these additional dosing patterns &ldquo;taper I&rdquo;, &ldquo;taper II&rdquo;, and &ldquo;alternating&rdquo; schedules. In the subsections below, we explain the structure of each of these schedules and present an example of <code>medExtractR_tapering</code> being applied to each.</p>

<p><em>Taper I</em></p>

<p>Taper I schedules are tapering regimens in which consecutive doses are explicitly written out. Examples of taper I schedules include:  </p>

<ul>
<li><p>&ldquo;prednisone 10 mg tablet 4 tablets by mouth daily for 2 weeks then 3 tablets by mouth daily for 1 week then 2 tablets by mouth daily for 1 week then 1.5 tablets by mouth daily for 1 week then 1 tablet by mouth daily for 1 week then 0.5 tablet by mouth daily for 1 week&rdquo;  </p></li>
<li><p>&ldquo;will increase prednisone to 15 mg once a day for 5-7 days, then taper (10 mg to 5 mg to off) over 2 weeks&rdquo;</p></li>
<li><p>&ldquo;prednisone 5 mg daily for 7 days and 2.5 mg daily for another 3 days&rdquo;  </p></li>
</ul>

<p>In a taper I schedule, at least some dose information is available for two or more segments of a weaning schedule. In the first example above, the strength of an individual tablet is provided up front, and each segment of the taper schedule just provides the number of tablets to take. This represents an ideal case where a clear duration is available for each segment. In the second example, the durations associated with each segment are less clear. MedExtractR only identifies the information exactly as it&#39;s written in a note, but a post-processing function could determine how to assign daily dosages given this information (e.g., 15 mg for 6 days, 10 mg for 7 days, 5 mg for 7 days, 0 mg). </p>

<!-- The `EHR` package provides a pipeline for converting raw medExtractR output of tapering schedules to a daily dose diary. -->

<pre><code class="r"># Taper 1 schedule
subset(pred_mxr, filename == sub(&quot;.+/&quot;, &quot;&quot;, pred_fn[1]))
</code></pre>

<pre><code>##                           filename      entity       expr     pos
## 1  predpid1_2013-04-27_note1_1.txt    DrugName prednisone 561:571
## 2  predpid1_2013-04-27_note1_1.txt    Strength      10 mg 572:577
## 3  predpid1_2013-04-27_note1_1.txt     DoseAmt          4 585:586
## 4  predpid1_2013-04-27_note1_1.txt       Route   by mouth 595:603
## 5  predpid1_2013-04-27_note1_1.txt   Frequency      daily 604:609
## 6  predpid1_2013-04-27_note1_1.txt Preposition        for 610:613
## 7  predpid1_2013-04-27_note1_1.txt    Duration    2 weeks 614:621
## 8  predpid1_2013-04-27_note1_1.txt  Transition       then 622:626
## 9  predpid1_2013-04-27_note1_1.txt     DoseAmt          3 627:628
## 10 predpid1_2013-04-27_note1_1.txt       Route   by mouth 637:645
## 11 predpid1_2013-04-27_note1_1.txt   Frequency      daily 646:651
## 12 predpid1_2013-04-27_note1_1.txt Preposition        for 652:655
## 13 predpid1_2013-04-27_note1_1.txt    Duration     1 week 656:662
## 14 predpid1_2013-04-27_note1_1.txt  Transition       then 663:667
## 15 predpid1_2013-04-27_note1_1.txt     DoseAmt          2 668:669
## 16 predpid1_2013-04-27_note1_1.txt       Route   by mouth 678:686
## 17 predpid1_2013-04-27_note1_1.txt   Frequency      daily 687:692
## 18 predpid1_2013-04-27_note1_1.txt Preposition        for 693:696
## 19 predpid1_2013-04-27_note1_1.txt    Duration     1 week 697:703
## 20 predpid1_2013-04-27_note1_1.txt  Transition       then 704:708
## 21 predpid1_2013-04-27_note1_1.txt     DoseAmt        1.5 709:712
## 22 predpid1_2013-04-27_note1_1.txt       Route   by mouth 721:729
## 23 predpid1_2013-04-27_note1_1.txt   Frequency      daily 730:735
## 24 predpid1_2013-04-27_note1_1.txt Preposition        for 736:739
## 25 predpid1_2013-04-27_note1_1.txt    Duration     1 week 740:746
## 26 predpid1_2013-04-27_note1_1.txt  Transition       then 747:751
## 27 predpid1_2013-04-27_note1_1.txt     DoseAmt          1 752:753
## 28 predpid1_2013-04-27_note1_1.txt       Route   by mouth 761:769
## 29 predpid1_2013-04-27_note1_1.txt   Frequency      daily 770:775
## 30 predpid1_2013-04-27_note1_1.txt Preposition        for 776:779
## 31 predpid1_2013-04-27_note1_1.txt    Duration     1 week 780:786
## 32 predpid1_2013-04-27_note1_1.txt  Transition       then 787:791
## 33 predpid1_2013-04-27_note1_1.txt     DoseAmt        0.5 792:795
## 34 predpid1_2013-04-27_note1_1.txt       Route   by mouth 803:811
## 35 predpid1_2013-04-27_note1_1.txt   Frequency      daily 812:817
## 36 predpid1_2013-04-27_note1_1.txt Preposition        for 818:821
## 37 predpid1_2013-04-27_note1_1.txt    Duration     1 week 822:828
</code></pre>

<p><em>Taper II</em></p>

<p>Taper II schedules are tapering regimens in which a repetitive dosing change is written more concisely. Typically, this is written in the form of <em>&ldquo;<initial dose> change by <incremental dose> at <interval>&rdquo;</em>. As an example, consider the phrase <em>&ldquo;Take prednisone 5mg tablet 4 tabs daily for one week, then decrease by 5mg every week then stop&rdquo;</em> In this excerpt, the patient&#39;s initial dose is 20 mg per day for a duration of one week. From the second part of the phrase, we can infer that after the first week, the patient&#39;s dosage will be 15 mg daily for the second week, 10 mg daily for the third week, 5 mg daily for the fourth week, and then 0 mg (off) after that. </p>

<!-- As part of the post-processing performed by the `EHR` package, some strength/dose strength expressions get reclassified as "dose increment," reflecting a recurring change within a tapering schedule  -->

<pre><code class="r"># Taper 2 schedule
subset(pred_mxr, filename == sub(&quot;.+/&quot;, &quot;&quot;, pred_fn[2]))
</code></pre>

<pre><code>##                           filename       entity          expr     pos
## 38 predpid2_2015-12-11_note1_1.txt     DrugName    prednisone 474:484
## 39 predpid2_2015-12-11_note1_1.txt     Strength          5 mg 485:489
## 40 predpid2_2015-12-11_note1_1.txt DoseStrength          20mg 502:506
## 41 predpid2_2015-12-11_note1_1.txt   IntakeTime every morning 507:520
## 42 predpid2_2015-12-11_note1_1.txt  Preposition           for 521:524
## 43 predpid2_2015-12-11_note1_1.txt     Duration       14 days 525:532
## 44 predpid2_2015-12-11_note1_1.txt   Transition          then 533:537
## 45 predpid2_2015-12-11_note1_1.txt   DoseChange      decrease 538:546
## 46 predpid2_2015-12-11_note1_1.txt  Preposition            by 547:549
## 47 predpid2_2015-12-11_note1_1.txt DoseStrength          5 mg 550:554
## 48 predpid2_2015-12-11_note1_1.txt     Duration  every 7 days 555:567
## 49 predpid2_2015-12-11_note1_1.txt  Preposition         until 568:573
## 50 predpid2_2015-12-11_note1_1.txt DoseSchedule          done 574:578
</code></pre>

<p><em>Alternating</em>  </p>

<p>Alternating schedules consist of a patient being on multiple doses (typically two), with different dosages on consecutive days. The patient may have two specific doses, for example <em>&ldquo;20mg of prednisone on even days and 10mg of prednisone on odd days&rdquo;</em>, or they may be on a single dose but taking it intermittently, for example <em>&ldquo;take prednisone 5mg tablet every other day for one week&rdquo;</em>.</p>

<pre><code class="r"># Alternating schedule
subset(pred_mxr, filename == sub(&quot;.+/&quot;, &quot;&quot;, pred_fn[3]))
</code></pre>

<pre><code>##                           filename       entity            expr     pos
## 51 predpid3_2017-01-01_note1_1.txt     DrugName            pred 630:634
## 52 predpid3_2017-01-01_note1_1.txt DoseStrength          2.5 mg 635:641
## 53 predpid3_2017-01-01_note1_1.txt        Route          orally 642:648
## 54 predpid3_2017-01-01_note1_1.txt    Frequency every other day 649:664
## 55 predpid3_2017-01-01_note1_1.txt DoseSchedule       alternate 665:674
## 56 predpid3_2017-01-01_note1_1.txt  Preposition            with 675:679
## 57 predpid3_2017-01-01_note1_1.txt DoseStrength            5 mg 680:684
## 58 predpid3_2017-01-01_note1_1.txt    Frequency every other day 685:700
</code></pre>

<p><strong>Note</strong>: It is possible for a dosing regimen to be written in a mixture of these cases. For example, the phrase <em>&ldquo;restart pred at 40 mg daily for 1 week, 30 mg daily for one week, 20 mg daily for one week and then drop by 5 mg per week after that&rdquo;</em> starts as a taper I schedule, but ends as a taper II schedule. An individual segment of a taper I schedule could also involve an alternating dose, particularly taking a single dose every other day in weaning schedules.</p>

<h3><code>medExtractR_tapering</code> development</h3>

<p>The tapering extension to medExtractR was developed on a set of 162 training notes from Vanderbilt University&#39;s de-identified EHR system, the Synthetic Derivative (SD). As a first step, we developed annotation guidelines as a way to rigorously define the definition of each new entity (or changes to any existing entity, if applicable). Two reviewers would then independently annotate each note, and a third party group would help resolve any discrepancies. The annotation guidelines were then updated, and annotations were revised, based on this process.</p>

<p>This set of training notes was also used to generate the default entity dictionaries included within the <code>medExtractR</code> package. The annotations, which serve as the gold standard for what information should be extracted, were used as the starting point for all dictionaries. Those expressions were then removed (e.g., mispelled words) or generalized using regular expressions (e.g., changing a &ldquo;2 days&rdquo; duration to &ldquo;\d{1,2} days&rdquo;, where \d represents any one or two digit number). Examples of some expressions in the new entity dictionaries are provided below: </p>

<ul>
<li><p>Duration: much of the duration dictionary is written using regular expressions to account for various numbers being used. Examples of expressions that would be considered durations are: <code>2 weeks</code>, <code>next 3 days</code>, <code>1 week ago</code>, <code>weekly</code>, <code>day five</code>, and dates (for example, to capture expressions like <em>&ldquo;Remain on prednisone 5mg daily until April 15&rdquo;</em>).</p></li>
<li><p>DoseSchedule: words indicating a specific dosing schedule (<code>taper</code>, <code>weaning</code>, <code>dose pack</code>, etc.) or stopping keywords (<code>off</code>, <code>stop</code>, <code>discontinue</code>, etc.)  </p></li>
<li><p>TimeKeyword: <code>was taking</code>, <code>yesterday</code>, <code>remain</code>, <code>tomorrow</code>, <code>current</code>, etc.</p></li>
<li><p>Transition: <code>then</code>, <code>followed by</code>, and punctuation such as <code>;</code> or <code>,</code>.</p></li>
<li><p>Preposition: <code>from</code>, <code>of</code>, <code>by</code>, <code>on</code>, <code>to</code>, <code>at</code>, etc. If a preposition is part of an expression for another entity (e.g., &ldquo;by&rdquo; in &ldquo;by mouth&rdquo;), then it is not extracted separately as a preposition.</p></li>
</ul>

<p>Before running <code>medExtractR_tapering</code>, we first pre-processed the notes by censoring any datetime expressions. The Duration entity can include date expressions, however it was common for the SD notes to have de-identified datetime expressions unrelated to dosing. Instead, these expressions typically reflected when the note was created, the time of the appointment, or when a prescription was faxed to the pharmacy. We also removed any notes that used an XML format, due to the structure of these notes being vastly different from the typical free-text clinical notes. XML, or &ldquo;extensive markup language,&rdquo; is a slightly more structured data format that includes tags to describe pieces of text within the note. The presence of such tags especially interfered with rule-based entities. For example, a dose amount of 3 tablets may appear as <code>&quot;&lt;DOSE_AMOUNT&gt;3&lt;/DOSE_AMOUNT&gt;&lt;DOSE_UNIT&gt;tablets&lt;/DOSE_UNIT&gt;&quot;</code>. The <code>medExtractR</code> system would typically consider a number followed by the word &ldquo;tablets&rdquo; to be a dose amount, but here the tag labels block these two expressions. Two XML-based notes were removed, resulting in 160 notes used for development.</p>

<h3>Details of <code>medExtractR_tapering</code> functionality</h3>

<p>The tapering extension of the <code>medExtractR</code> function is capable of extracting more entities associated with tapering schedules, and is thus more flexible than the basic version of <code>medExtractR</code>. The arguments between the basic and extended versions of <code>medExtractR</code> are the same with one major exception: <code>medExtractR_tapering</code> does <em>not</em> have an argument for <code>window_length</code>. This is because the length of the window in which all relevant entities are contained varies greatly depending on the type of dosing schedule (e.g., taper I, taper II, or alternating). Unlike the basic <code>medExtractR</code> function, which uses a fixed window length, <code>medExtractR_tapering</code> dynamically generates a search window. This is done by first allowing a very generous search window, and then truncating based on two criteria: (1) the presence of competing drug names or terms; and (2) the distance between consecutive entities. The user can modify this search window process by adding or removing terms to the <code>drug_list</code> argument, for example including additional categories of competing terms to use for truncation (e.g., symptoms, procedure, or laboratory names).</p>

<pre><code class="r">note &lt;- paste(scan(filename, &#39;&#39;, sep = &#39;\n&#39;, quiet = TRUE), collapse = &#39;\n&#39;)
medExtractR_tapering(note, drug_names, unit, max_dist, ...)
</code></pre>

<p>The remainder of this section outlines how <code>medExtractR_tapering</code> processes a note, from free-text input to a structured entity-level output. We&#39;ll use the following excerpt as our example input to help illustrate how the output changes at each step.</p>

<pre><code>Chief complaint/Reason for Visit: 4mo follow up
History of Present Illness: No muscle pain since prior visit. Does report increased fatigue.
Also reports R hand tremor intermittently. 
Medications: 
- Lialda 1.2 gram tablet,delayed release 4 tablets by mouth daily 
- prednisone 5mg 2 tablets by mouth daily 
- omeprazole 20 mg one tablet by mouth daily 
Allergies: 
- Penicillins (severe hives)
Past Medical and Surgical History: I have reviewed the problem list and there is no change
since last visit. 
Social History: 
Exercise - no change since last visit 
Tobacco - no smoking 
Ethanol - 1 drink per week
Employment - no change since last visit 
Impression &amp; Plan: 
Doing very well today w/o symptoms and good muscle strength on exam. 
1. Check CBC, CMP, CK today, and will have pt check CBC locally in 3mo 
2. Taper prednisone: 10mg daily for 7 days then 5mg daily for 7 days then decrease by 1mg
every 7 days until done. Patient is on track with schedule.  
3. Continue azathioprine at 200mg daily 4. Can continue to hold alendronate Follow up in
6 months. 
</code></pre>

<p><em>Step 1</em>: Initially, the search window is defined from the end of the previous drug mention (or the start of the note) up until the start of the next drug mention (or the end of the note). From there, <code>medExtractR_tapering</code> relies heavily upon expressions within the <code>drug_list</code> argument to further shorten the search window, truncating at the closest match on either side of the drug name of interest. The default <code>drug_list</code> is based on cleaned and formatted extractions from RxNorm\(^{3}\) just like the basic version of <code>medExtractR</code>. This search window is what <code>medExtractR_tapering</code> provides to the <code>extract_entities_tapering</code> function for each drug mention.  </p>

<p>Example: In our example note, there are two mentions of prednisone. For mention #1, the drug names &ldquo;Lialda&rdquo; (before) and &ldquo;omeprazole&rdquo; (after) serve as the boundaries of the search window. For mention #2, &ldquo;Ethanol&rdquo; (before) and &ldquo;azathioprine&rdquo; (after) are the boundaries. The search window for each mention would be:</p>

<pre><code>MENTION 1:
1.2 gram tablet,delayed release 4 tablets by mouth daily
- prednisone 5mg 2 tablets by mouth daily 
- 

MENTION 2:
 - 1 drink per week
Employment - no change since last visit 
Impression &amp; Plan: 
Doing very well today w/o symptoms and good muscle strength on exam. 
1. Check CBC, CMP, CK today, and will have pt check CBC locally in 3mo 
2. Taper prednisone: 10mg daily for 7 days then 5mg daily for 7 days then decrease by
1mg every 7 days until done. Patient is on track with schedule.
3. Continue 
</code></pre>

<p>Note that these are assuming <code>drug_list</code> incorporates only drug names, which is the default. If the user chose to augment this list with symptoms, procedures, or laboratory names, the starting point window for mention #2 could be shortened to just after &ldquo;CBC&rdquo; (complete blood count).</p>

<p><em>Step 2</em>: The <code>extract_entities_tapering</code> function extracts all entities found within the initial search window. Strength, dose amount, dose strength, dispense amount, and refill are rule-based entities; all others are primarily dictionary-based. In the basic version of <code>medExtractR</code>, if a strength-like expression (e.g., &ldquo;10 mg&rdquo;) appears in a search window with no dose amount, we would classify that as dose strength. However, in tapering schedules, it is common to have a mix of information within the same phrase, e.g., <em>&ldquo;prednisone 10mg tablet 20mg (2 tabs) daily for 2 weeks then 10mg (1 tab) daily for 2 weeks&rdquo;</em>. For this reason, <code>medExtractR</code> relies more on the context of each strength expression to determine whether it is a strength or a dose strength. For example, if the strength expression is followed by the word &ldquo;tablet&rdquo; (or capsule, pill, etc.), we consider it to be &ldquo;Strength&rdquo; (i.e., the amount of drug per dosage unit).</p>

<p>Example: Below, we see that <code>medExtractR</code> initially extracts all entities it identifies within the search windows above. Note that for mention #1, &ldquo;1.2 gram&rdquo; is not extracted as a strength because for prednisone, we set <code>unit = &quot;mg&quot;</code>, and hence &ldquo;gram&rdquo; is not a relevant unit.</p>

<pre><code>MENTION 1:
   entity        expr     pos
  DoseAmt           4 250:251
    Route    by mouth 252:260
Frequency       daily 261:266
 DrugName  prednisone 269:279
 Strength         5mg 280:283
  DoseAmt           2 284:285
    Route    by mouth 294:302
Frequency       daily 303:308


MENTION 2:
      entity         expr     pos
    Duration     per week 603:611
DoseSchedule        Taper 818:823
    DrugName   prednisone 824:834
DoseStrength         10mg 836:840
   Frequency        daily 841:846
 Preposition          for 847:850
    Duration       7 days 851:857
  Transition         then 858:862
DoseStrength          5mg 863:866
   Frequency        daily 867:872
 Preposition          for 873:876
    Duration       7 days 877:883
  Transition         then 884:888
  DoseChange     decrease 889:897
 Preposition           by 898:900
DoseStrength          1mg 901:904
    Duration every 7 days 905:917
 Preposition        until 918:923
DoseSchedule         done 924:928
 Preposition           on 941:943
 Preposition         with 950:954
 TimeKeyword     Continue 970:978
</code></pre>

<p><em>Step 3</em>: After extracting all entities but before returning results, <code>extract_entities_tapering</code> attempts to remove entities that are not likely to be associated with the drug name of interest. This is done by considering the gap, in number of characters, between consecutive entities both before and after the drug mention (the transition, preposition, and time keyword entities are excluded from this procedure due to the high potential for false positives). If this gap exceeds 50 characters, we remove all extracted entities at and further from the drug mention. The value of 50 characters was selected based on gold standard annotations on a training set of notes. Finally, we remove any prepositions or transitions from the very start or very end of the extractions, as these are primarily linkage entities and would require information on either side.</p>

<p>Example: There are no changes to mention #1 for this step. For mention #2, the first duration extraction of &ldquo;per week&rdquo; (<code>603:611</code>) has a gap of 207 characters until the next extraction of &ldquo;Taper&rdquo; (<code>818:823</code>). Since this exceeds the gap size of 50 characters, &ldquo;per week&rdquo; is removed as an unrelated entity.</p>

<pre><code>MENTION 1:
   entity        expr     pos
 DrugName  prednisone 269:279
 Strength         5mg 280:283
  DoseAmt           2 284:285
    Route    by mouth 294:302
Frequency       daily 303:308


MENTION 2:
      entity         expr     pos
DoseSchedule        Taper 818:823
    DrugName   prednisone 824:834
DoseStrength         10mg 836:840
   Frequency        daily 841:846
 Preposition          for 847:850
    Duration       7 days 851:857
  Transition         then 858:862
DoseStrength          5mg 863:866
   Frequency        daily 867:872
 Preposition          for 873:876
    Duration       7 days 877:883
  Transition         then 884:888
  DoseChange     decrease 889:897
 Preposition           by 898:900
DoseStrength          1mg 901:904
    Duration every 7 days 905:917
 Preposition        until 918:923
DoseSchedule         done 924:928
 Preposition           on 941:943
 Preposition         with 950:954
 TimeKeyword     Continue 970:978
</code></pre>

<p><em>Step 4</em>: With the results returned from <code>extract_entities_tapering</code>, <code>medExtractR_tapering</code> performs some additional processing to reduce false positives. First, we look for the first occurrence of punctuation before the drug name (e.g., a period or line break), and remove all entities before that punctuation. For example, in the phrase <em>&ldquo;&hellip;Patient was previously taking omeprazole 20mg per day. Currently on prednisone 10mg daily&hellip;&rdquo;</em>, the information &ldquo;20mg&rdquo; and &ldquo;per day&rdquo; would initially be extracted, since the window wouldn&#39;t truncate until the end of the competing drug name &ldquo;omeprazole.&rdquo; However, since there is a period between the two sentences, <code>medExtractR_tapering</code> would assume &ldquo;20mg&rdquo; and &ldquo;per day&rdquo; were not related to prednisone, and thus remove them from the results. The one exception is if the adjacent entity is a preposition, which indicates it may be linking the drug mention of interest to other dosing information (e.g., <em>&ldquo;20mg of\nprednisone&rdquo;</em>, where &ldquo;\n&rdquo; is a line break). If the search window was truncated due to another drug name, we check to see if any of the entities we extracted are immediately adjacent (within 2 characters) to the competing drug name. If so, we continue to remove immediately adjacent entities until a gap of more than two characters occur (ignoring any mentions of &ldquo;tablet&rdquo; next to dose amount or strength), at which point we no longer attribute those extractions to the competing drug name.  </p>

<p>Example: For mention #1 in our example, when we look at excerpt of the note between prednisone and the closest preceding entity, we see &ldquo;daily\n- prednisone&rdquo;, where &ldquo;\n&rdquo; is a line break. Since there is punctuation between these two entities (in this case, either \n or - would be sufficient even without the other), we remove the extraction &ldquo;daily&rdquo; as well as all other extractions before it.</p>

<p>For mention #2, the search window was shortened by the presence of the drug name &ldquo;azathioprine&rdquo;, and <code>medExtractR</code> stores the position of this competing drug name (<code>979:991</code>). Since &ldquo;Continue&rdquo; was extracted immediately before the competing drug name (<code>970:978</code>), we remove it from our results. No other entities are removed since there&#39;s a gap between &ldquo;Continue&rdquo; and the next preceding entity (&ldquo;with&rdquo; at <code>950:954</code>).</p>

<pre><code>MENTION 1:
   entity        expr     pos
 DrugName  prednisone 269:279
 Strength         5mg 280:283
  DoseAmt           2 284:285
    Route    by mouth 294:302
Frequency       daily 303:308


MENTION 2:
      entity         expr     pos
DoseSchedule        Taper 818:823
    DrugName   prednisone 824:834
DoseStrength         10mg 836:840
   Frequency        daily 841:846
 Preposition          for 847:850
    Duration       7 days 851:857
  Transition         then 858:862
DoseStrength          5mg 863:866
   Frequency        daily 867:872
 Preposition          for 873:876
    Duration       7 days 877:883
  Transition         then 884:888
  DoseChange     decrease 889:897
 Preposition           by 898:900
DoseStrength          1mg 901:904
    Duration every 7 days 905:917
 Preposition        until 918:923
DoseSchedule         done 924:928
 Preposition           on 941:943
 Preposition         with 950:954
</code></pre>

<p>The preposition and transition entities also have some additional rules applied, considering how common the expressions in these dictionaries are (e.g., &ldquo;of&rdquo;, &ldquo;to&rdquo;, &ldquo;then&rdquo;, &ldquo;;&rdquo; or &ldquo;,&rdquo;). For both of these entities, the extraction must occur immediately adjacent to another extracted entity. Furthermore, for transition we require some sort of dose-relevant information to be extracted nearby (within 10 characters) on both sides. &ldquo;Dose-relevant&rdquo; entities include strength, dose amount, dose strength, frequency, intake time, duration, and dose schedule (for stopping keywords). Though less common, the same issue exists for the time keyword entity (common expressions include &ldquo;was&rdquo;, &ldquo;will&rdquo;, etc.). Rather than enforcing a character distance around time keyword extractions, we allow one word (of any length) to occur between time keyword and an adjacent entity. </p>

<p>Example: There are no further changes to mention #1. For mention #2, the prepositions &ldquo;on&rdquo; (<code>941:943</code>) and &ldquo;with&rdquo; (<code>950:954</code>) meet two separate conditions for removal; first, they are not immediately adjacent to another extracted entity and second, they occur at the very end of the group and we don&#39;t allow the last entity to be a preposition or transition. <code>medExtractR_tapering</code> combines any output from each drug mention, so the final output is:</p>

<pre><code>      entity         expr     pos
    DrugName   prednisone 269:279
    Strength          5mg 280:283
     DoseAmt            2 284:285
       Route     by mouth 294:302
   Frequency        daily 303:308
DoseSchedule        Taper 818:823
    DrugName   prednisone 824:834
DoseStrength         10mg 836:840
   Frequency        daily 841:846
 Preposition          for 847:850
    Duration       7 days 851:857
  Transition         then 858:862
DoseStrength          5mg 863:866
   Frequency        daily 867:872
 Preposition          for 873:876
    Duration       7 days 877:883
  Transition         then 884:888
  DoseChange     decrease 889:897
 Preposition           by 898:900
DoseStrength          1mg 901:904
    Duration every 7 days 905:917
 Preposition        until 918:923
DoseSchedule         done 924:928
</code></pre>

<h2>References</h2>

<ol>
<li><p>Weeks HL, Beck C, McNeer E, Williams ML, Bejan CA, Denny JC, Choi L. medExtractR: A targeted, customizable approach to medication extraction from electronic health records. Journal of the American Medical Informatics Association. 2020 Mar;27(3):407-18. doi: 10.1093/jamia/ocz207.</p></li>
<li><p>Choi L, Beck C, Weeks HL, and McNeer E (2020). EHR: Electronic Health Record (EHR) Data
Processing and Analysis Tool. R package version 0.3-1. <a href="https://CRAN.R-project.org/package=EHR">https://CRAN.R-project.org/package=EHR</a></p></li>
<li><p>Nelson SJ, Zeng K, Kilbourne J, Powell T, Moore R. Normalized names for clinical drugs: RxNorm at 6 years. J Am Med Inform Assoc. 2011 Jul-Aug;18(4)441-8. doi: 10.1136/amiajnl-2011-000116. Epub 2011 Apr 21. PubMed PMID: 21515544; PubMed Central PMCID: PMC3128404.</p></li>
</ol>

</body>

</html>
